name: Latest release

on:
  push:
    branches: !-stable

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Clippy
        run: |
          rustup component add clippy
          cargo clippy
      - name: Format
        run: rustup run stable cargo fmt -- --check
      - name: Check
        run: cargo check
      - name: Build
        run: cargo build
      - name: Run Tests
        run: cargo test --workspace